export const PrLinesData: any = [
  {
    LINE_NO: 66989,
    ITEM_CODE: 'PR23014617',
    DESCRIPTION: 'Level Switches for O&amp;M',
    CREATION_DATE: '57:56.0',
    ApprovedDate: '29:59.3',
    SiteName: 113,
    PROJECT_NAME: 'NULL',
    DEPARTMENTNAME: '2331 - Electrical &amp; Instrumentation',
    PRTYPE: 'Revenue Supply',
    PRSubType: 'General',
    REQUESTED_BY: 'Surendra Kumar Soni',
    TotalValue: 38370,
    AssignBuyer: 'VIJAY CHAPLOT',
    BUYERSTATUS: 'In Process',
    QUANTITY: 20,
    IN_PROCESS_QUANTITY: 10,
    USED_QUANITTY: 2,
    REMANING_QUANITTY: 1,
    RATE: 20,
    AMOUNT: 100.0,
    STATUS: 'PENDING',
    REQ_STATUS: 'PENDING',
    REQ_NO: '123665',
    PO_NO: 12313,
    STATE: 'Haryana',
  },
  {
    LINE_NO: 66963,
    ITEM_CODE: 'PR230123132',
    STATE: 'Haryana',
    PO_NO: 12363,
    REQ_NO: '123665',
    REQ_STATUS: 'PENDING',
    STATUS: 'PENDING',
    AMOUNT: 100.0,
    RATE: 20,
    REMANING_QUANITTY: 1,
    IN_PROCESS_QUANTITY: 2,
    USED_QUANITTY: 1,
    QUANTITY: 12,
    prid: 66854,
    PR_NUM: 'PR23014484',
    DESCRIPTION: 'Pneumatic Fittings for Bag Filter Modification',
    CREATION_DATE: '09:15.0',
    ApprovedDate: '44:44.6',
    SiteName: 113,
    PROJECT_NAME: 'NULL',
    DEPARTMENTNAME: '2331 - Electrical &amp; Instrumentation',
    PRTYPE: 'Revenue Supply',
    PRSubType: 'Breakdown',
    REQUESTED_BY: 'Surendra Kumar Soni',
    TotalValue: 2800,
    AssignBuyer: 'VIJAY CHAPLOT',
    BUYERSTATUS: 'Pending',
  },
];

const PR_RequestionLineDetail = [
  //  { {
  //     Site: '',
  //     PRNumber: '',
  //     PRTYpe: '',
  //     PrSubType: '',
  //     RequestDate: '',
  //     ProjectDate: '',
  //     ProjectId: '',
  //     PR: '',
  //     TEFRID: '',
  //     ConsumptionDate: '',
  //     BusinessJustificationDate: '',
  //     workOrderNumber: '',
  //     TotalValue: '',
  //     Status: ' ',
  //     Reqeuster: ' ',
  //     Department: '',
  //   },}
];

// export let PohistoryData = [
//   {
//     Vendor_Code: '107812',
//     Vendor_Name: 'M.R.Organisation Limited',
//     PO_No: '102PO2205339',
//     PO_Confirmation_Date: '12/10/2021',
//     PO_Qty: '3.00',
//     UOM: 'NOS',
//     Unit_Price: '2000.00',
//     Discount: '20.00',
//   },
// ];

export let PohistoryData = [
  {
    Vendor_Code: '109339',
    Vendor_Name: 'Cable Connectronics',
    PO_No: '102PO2308947',
    PO_Confirmation_Date: '14/02/2023',
    PO_Qty: '2.00',
    UOM: 'NOS',
    Unit_Price: '750.00',
    Discount: '0.00',
  },
  {
    Vendor_Code: '109339',
    Vendor_Name: 'Cable Connectronics',
    PO_No: '102PO2307716',
    PO_Confirmation_Date: '02/01/2023',
    PO_Qty: '10.00',
    UOM: 'NOS',
    Unit_Price: '750.00',
    Discount: '0.00',
  },
  {
    Vendor_Code: '102608',
    Vendor_Name: 'Instrumentation store',
    PO_No: '102PO2200635',
    PO_Confirmation_Date: '13/04/2021',
    PO_Qty: '5.00',
    UOM: 'NOS',
    Unit_Price: '1115.00',
    Discount: '0.00',
  },
];
