export const Po_or_RFQOrder = [
  {
    Site: 102,
    Warehouse: '102018',
    Buyer_Group: 'P&LI',
    Item_Group: '',
    PPO_No: 'WCL23PPO-377159',
    PPO_Date: '27/02/2023',
    Item_Code: 100049516,
    Item_Description: 'CHEMICAL;GRINDING AID TABLETS;SOLID,PLASTIC BOTTLE',
    Config: 'THYSSENKRUPP',
    UOM: 'NOS',
    Min_Order_Qty: 0.0,
    Max_Order_Qty: 0.0,
    On_Hand_Qty_in_Main_Store_Warehouse: 0.0,
    Required_Qty: 11,
    On_Hand_Qty_in_Other_Store_Warehouse: 0.0,
    Pending_PO: 0.0,
    PO_In_Process: 0.0,
    In_Process_PR: 0.0,
    NetOrder_Qty: 11,
    Ordered_Qty: 0.0,
    Order_Qty: 11,
    Pending_PR: 0.0,
    PR_InReview: 0.0,
    Last_Purchase_Price: 17000.0,
    PPO_Amount: 187000.0,
    Last_PO_No: '',
    Last_PO_Date: '',
    Vendor_Name: '',
    Total_Consumption_for_365_days: 0.0,
  },
  {
    Site: 102,
    Warehouse: '102018',
    Buyer_Group: 'P&LI',
    Item_Group: '',
    PPO_No: 'WCL23PPO-378398',
    PPO_Date: '27/02/2023',
    Item_Code: 100049516,
    Item_Description: 'CHEMICAL;GRINDING AID TABLETS;SOLID,PLASTIC BOTTLE',
    Config: 'THYSSENKRUPP',
    UOM: 'NOS',
    Min_Order_Qty: 0.0,
    Max_Order_Qty: 0.0,
    On_Hand_Qty_in_ain_Store_Warehouse: 0.0,
    Required_Qty: 11,
    On_Hand_Qty_in_Other_Store_Warehouse: 0.0,
    Pending_PO: 0.0,
    PO_In_Process: 0.0,
    In_Process_PR: 0.0,
    NetOrder_Qty: 0.0,
    Ordered_Qty: 0.0,
    Order_Qty: 0.0,
    Pending_PR: 0.0,
    PR_InReview: 0.0,
    Last_Purchase_Price: 17000.0,
    PPO_Amount: 187000.0,
    Last_PO_No: '',
    Last_PO_Date: '',
    Vendor_Name: '',
    Total_Consumption_for_365_days: 0.0,
  },
  {
    Site: 102,
    Warehouse: '102018',
    Buyer_Group: 'P&LI',
    Item_Group: '',
    PPO_No: 'WCL23PPO-379643',
    PPO_Date: '27/02/2023',
    Item_Code: 100049516,
    Item_Description: 'CHEMICAL;GRINDING AID TABLETS;SOLID,PLASTIC BOTTLE',
    Config: 'THYSSENKRUPP',
    UOM: 'NOS',
    Min_Order_Qty: 0.0,
    Max_Order_Qty: 0.0,
    On_Hand_Qty_in_ain_Store_Warehouse: 0.0,
    Required_Qty: 11,
    On_Hand_Qty_in_Other_Store_Warehouse: 0.0,
    Pending_PO: 0.0,
    PO_In_Process: 0.0,
    In_Process_PR: 0.0,
    NetOrder_Qty: 11,
    Ordered_Qty: 0.0,
    Order_Qty: 11,
    Pending_PR: 0.0,
    PR_InReview: 0.0,
    Last_Purchase_Price: 17000.0,
    PPO_Amount: 187000.0,
    Last_PO_No: '',
    Last_PO_Date: '',
    Vendor_Name: '',
    Total_Consumption_for_365_days: 0.0,
  },
  {
    Site: 102,
    Warehouse: '102018',
    Buyer_Group: 'P&LI',
    Item_Group: '',
    PPO_No: 'WCL23PPO-380895',
    PPO_Date: '27/02/2023',
    Item_Code: 100049516,
    Item_Description: 'CHEMICAL;GRINDING AID TABLETS;SOLID,PLASTIC BOTTLE',
    Config: 'THYSSENKRUPP',
    UOM: 'NOS',
    Min_Order_Qty: 0.0,
    Max_Order_Qty: 0.0,
    On_Hand_Qty_in_ain_Store_Warehouse: 0.0,
    Required_Qty: 11,
    On_Hand_Qty_in_Other_Store_Warehouse: 0.0,
    Pending_PO: 0.0,
    PO_In_Process: 0.0,
    In_Process_PR: 0.0,
    NetOrder_Qty: 0.0,
    Ordered_Qty: 0.0,
    Order_Qty: 0.0,
    Pending_PR: 0.0,
    PR_InReview: 0.0,
    Last_Purchase_Price: 17000.0,
    PPO_Amount: 187000.0,
    Last_PO_No: '',
    Last_PO_Date: '',
    Vendor_Name: '',
    Total_Consumption_for_365_days: 0.0,
  },
  {
    Site: 102,
    Warehouse: '102018',
    Buyer_Group: 'P&LI',
    Item_Group: '',
    PPO_No: 'WCL23PPO-382150',
    PPO_Date: '27/02/2023',
    Item_Code: 100049516,
    Item_Description: 'CHEMICAL;GRINDING AID TABLETS;SOLID,PLASTIC BOTTLE',
    Config: 'THYSSENKRUPP',
    UOM: 'NOS',
    Min_Order_Qty: 0.0,
    Max_Order_Qty: 0.0,
    On_Hand_Qty_in_ain_Store_Warehouse: 0.0,
    Required_Qty: 11,
    On_Hand_Qty_in_Other_Store_Warehouse: 0.0,
    Pending_PO: 0.0,
    PO_In_Process: 0.0,
    In_Process_PR: 0.0,
    NetOrder_Qty: 11,
    Ordered_Qty: 0.0,
    Order_Qty: 11,
    Pending_PR: 0.0,
    PR_InReview: 0.0,
    Last_Purchase_Price: 17000.0,
    PPO_Amount: 187000.0,
    Last_PO_No: '',
    Last_PO_Date: '',
    Vendor_Name: '',
    Total_Consumption_for_365_days: 0.0,
  },
  {
    Site: 102,
    Warehouse: '102018',
    Buyer_Group: 'P&LI',
    Item_Group: '',
    PPO_No: 'WCL23PPO-383391',
    PPO_Date: '27/02/2023',
    Item_Code: 100049516,
    Item_Description: 'CHEMICAL;GRINDING AID TABLETS;SOLID,PLASTIC BOTTLE',
    Config: 'THYSSENKRUPP',
    UOM: 'NOS',
    Min_Order_Qty: 0.0,
    Max_Order_Qty: 0.0,
    On_Hand_Qty_in_ain_Store_Warehouse: 0.0,
    Required_Qty: 11,
    On_Hand_Qty_in_Other_Store_Warehouse: 0.0,
    Pending_PO: 0.0,
    PO_In_Process: 0.0,
    In_Process_PR: 0.0,
    NetOrder_Qty: 0.0,
    Ordered_Qty: 0.0,
    Order_Qty: 0.0,
    Pending_PR: 0.0,
    PR_InReview: 0.0,
    Last_Purchase_Price: 17000.0,
    PPO_Amount: 187000.0,
    Last_PO_No: '',
    Last_PO_Date: '',
    Vendor_Name: '',
    Total_Consumption_for_365_days: 0.0,
  },
  {
    Site: 102,
    Warehouse: '102018',
    Buyer_Group: 'P&LI',
    Item_Group: '',
    PPO_No: 'WCL23PPO-384632',
    PPO_Date: '27/02/2023',
    Item_Code: 100049516,
    Item_Description: 'CHEMICAL;GRINDING AID TABLETS;SOLID,PLASTIC BOTTLE',
    Config: 'THYSSENKRUPP',
    UOM: 'NOS',
    Min_Order_Qty: 0.0,
    Max_Order_Qty: 0.0,
    On_Hand_Qty_in_ain_Store_Warehouse: 0.0,
    Required_Qty: 11,
    On_Hand_Qty_in_Other_Store_Warehouse: 0.0,
    Pending_PO: 0.0,
    PO_In_Process: 0.0,
    In_Process_PR: 0.0,
    NetOrder_Qty: 11,
    Ordered_Qty: 0.0,
    Order_Qty: 11,
    Pending_PR: 0.0,
    PR_InReview: 0.0,
    Last_Purchase_Price: 17000.0,
    PPO_Amount: 187000.0,
    Last_PO_No: '',
    Last_PO_Date: '',
    Vendor_Name: '',
    Total_Consumption_for_365_days: 0.0,
  },
];
