export const prGridDataForRfq: any =  
    [
        {
            "sNo": 1,
            "prid": 66789,
            "pR_NUM": "PR23014419",
            "prepareR_ID": 27220,
            "description": "Load Unload valve and Kit required for Compressor.",
            "enterby": "Arpit Nagar",
            "enterdate": "2023-02-09T22:41:34.95",
            "approvedDate": "2023-02-11T12:23:20.923",
            "siteId": 8,
            "siteName": "110",
            "projecT_NAME": null,
            "departmentCode": null,
            "departmentName": "2331 - Electrical & Instrumentation",
            "prtype": "Revenue Supply",
            "prSubType": "General",
            "preparer": "Arpit Nagar",
            "totalValue": 20000,
            "assignBuyer": "VIJAY CHAPLOT",
            "pR_STATUS": "Approved",
            "buyerstatus": "In Process",
            "totalcount": 14,
            "prLinesData":[
                {
                  "prtransid": 131796,
                  "prid": 66789,
                  "pR_NUM": "",
                  "itemcode": "100053031",
                  "iteM_DESCRIPTION": "VALVE ASSEMBLY; TYPE: LOAD UNLOAD,COMBIN. AUXILIARY; MANUFACTURER PART NO: 205831E3, MANUFACTURER: KAESER, MODEL/MACHINE NO: G3/4XQ16",
                  "uom": "NOS",
                  "quantity": 1,
                  "inProcessQUANTITY": 0,
                  "usedQty": 0,
                  "remQty": 1,
                  "rate": 15000,
                  "netAmount": 15000,
                  "buyerstatus": "In Process",
                  "rfqStatus": "Published",
                  "rfqno": "3223",
                  "poNo": "",
                  "poid": 0,
                  "stateName": "Madhya Pradesh",
                  "buyerid": 27043,
                  "siteID": 8,
                  "assignBuyer": "VIJAY CHAPLOT"
                },
                {
                  "prtransid": 131797,
                  "prid": 66789,
                  "pR_NUM": "",
                  "itemcode": "100053032",
                  "iteM_DESCRIPTION": "KIT, COMPRESSOR REPAIR; TYPE: MAINTENANCE OF AUX.VALVE; MANUFACTURER PART NO: 400940.2, MANUFACTURER: KAESER",
                  "uom": "NOS",
                  "quantity": 1,
                  "inProcessQUANTITY": 0,
                  "usedQty": 0,
                  "remQty": 1,
                  "rate": 5000,
                  "netAmount": 5000,
                  "buyerstatus": "In Process",
                  "rfqStatus": "Published",
                  "rfqno": "3223",
                  "poNo": "",
                  "poid": 0,
                  "stateName": "Madhya Pradesh",
                  "buyerid": 27043,
                  "siteID": 8,
                  "assignBuyer": "VIJAY CHAPLOT"
                }
              ]
        },
        {
            "sNo": 2,
            "prid": 66778,
            "pR_NUM": "PR23014408",
            "prepareR_ID": 27190,
            "description": "Float level switch for water tank",
            "enterby": "Sumit jain",
            "enterdate": "2023-02-09T17:08:49.51",
            "approvedDate": "2023-02-11T19:03:43.56",
            "siteId": 2,
            "siteName": "102",
            "projecT_NAME": null,
            "departmentCode": null,
            "departmentName": "2321 - Instrumentation",
            "prtype": "Revenue Supply",
            "prSubType": "General",
            "preparer": "Sumit jain",
            "totalValue": 1500,
            "assignBuyer": "VIJAY CHAPLOT",
            "pR_STATUS": "Approved",
            "buyerstatus": "Closed",
            "totalcount": 14,
            "prLinesData":[
                {
                  "prtransid": 131796,
                  "prid": 66789,
                  "pR_NUM": "",
                  "itemcode": "100053031",
                  "iteM_DESCRIPTION": "VALVE ASSEMBLY; TYPE: LOAD UNLOAD,COMBIN. AUXILIARY; MANUFACTURER PART NO: 205831E3, MANUFACTURER: KAESER, MODEL/MACHINE NO: G3/4XQ16",
                  "uom": "NOS",
                  "quantity": 1,
                  "inProcessQUANTITY": 0,
                  "usedQty": 0,
                  "remQty": 1,
                  "rate": 15000,
                  "netAmount": 15000,
                  "buyerstatus": "In Process",
                  "rfqStatus": "Published",
                  "rfqno": "3223",
                  "poNo": "",
                  "poid": 0,
                  "stateName": "Madhya Pradesh",
                  "buyerid": 27043,
                  "siteID": 8,
                  "assignBuyer": "VIJAY CHAPLOT"
                },
                {
                  "prtransid": 131797,
                  "prid": 66789,
                  "pR_NUM": "",
                  "itemcode": "100053032",
                  "iteM_DESCRIPTION": "KIT, COMPRESSOR REPAIR; TYPE: MAINTENANCE OF AUX.VALVE; MANUFACTURER PART NO: 400940.2, MANUFACTURER: KAESER",
                  "uom": "NOS",
                  "quantity": 1,
                  "inProcessQUANTITY": 0,
                  "usedQty": 0,
                  "remQty": 1,
                  "rate": 5000,
                  "netAmount": 5000,
                  "buyerstatus": "In Process",
                  "rfqStatus": "Published",
                  "rfqno": "3223",
                  "poNo": "",
                  "poid": 0,
                  "stateName": "Madhya Pradesh",
                  "buyerid": 27043,
                  "siteID": 8,
                  "assignBuyer": "VIJAY CHAPLOT"
                }
              ]
        },
        {
            "sNo": 3,
            "prid": 66775,
            "pR_NUM": "PR23014405",
            "prepareR_ID": 27373,
            "description": "Load cell require for replacement at cement weigh bridge.",
            "enterby": "Manish Purohit",
            "enterdate": "2023-02-09T16:50:32.11",
            "approvedDate": "2023-02-11T19:09:40.643",
            "siteId": 2,
            "siteName": "102",
            "projecT_NAME": null,
            "departmentCode": null,
            "departmentName": "2321 - Instrumentation",
            "prtype": "Revenue Supply",
            "prSubType": "General",
            "preparer": "Manish Purohit",
            "totalValue": 100000,
            "assignBuyer": "VIJAY CHAPLOT",
            "pR_STATUS": "Approved",
            "buyerstatus": "In Process",
            "totalcount": 14,
            "prLinesData":[
                {
                  "prtransid": 131796,
                  "prid": 66789,
                  "pR_NUM": "",
                  "itemcode": "100053031",
                  "iteM_DESCRIPTION": "VALVE ASSEMBLY; TYPE: LOAD UNLOAD,COMBIN. AUXILIARY; MANUFACTURER PART NO: 205831E3, MANUFACTURER: KAESER, MODEL/MACHINE NO: G3/4XQ16",
                  "uom": "NOS",
                  "quantity": 1,
                  "inProcessQUANTITY": 0,
                  "usedQty": 0,
                  "remQty": 1,
                  "rate": 15000,
                  "netAmount": 15000,
                  "buyerstatus": "In Process",
                  "rfqStatus": "Published",
                  "rfqno": "3223",
                  "poNo": "",
                  "poid": 0,
                  "stateName": "Madhya Pradesh",
                  "buyerid": 27043,
                  "siteID": 8,
                  "assignBuyer": "VIJAY CHAPLOT"
                },
                {
                  "prtransid": 131797,
                  "prid": 66789,
                  "pR_NUM": "",
                  "itemcode": "100053032",
                  "iteM_DESCRIPTION": "KIT, COMPRESSOR REPAIR; TYPE: MAINTENANCE OF AUX.VALVE; MANUFACTURER PART NO: 400940.2, MANUFACTURER: KAESER",
                  "uom": "NOS",
                  "quantity": 1,
                  "inProcessQUANTITY": 0,
                  "usedQty": 0,
                  "remQty": 1,
                  "rate": 5000,
                  "netAmount": 5000,
                  "buyerstatus": "In Process",
                  "rfqStatus": "Published",
                  "rfqno": "3223",
                  "poNo": "",
                  "poid": 0,
                  "stateName": "Madhya Pradesh",
                  "buyerid": 27043,
                  "siteID": 8,
                  "assignBuyer": "VIJAY CHAPLOT"
                }
              ]
        },
        {
            "sNo": 4,
            "prid": 66774,
            "pR_NUM": "PR23014404",
            "prepareR_ID": 27190,
            "description": "Angle valve for Nitrogen generator plant",
            "enterby": "Sumit jain",
            "enterdate": "2023-02-09T16:46:58.977",
            "approvedDate": "2023-02-11T19:04:01.243",
            "siteId": 2,
            "siteName": "102",
            "projecT_NAME": null,
            "departmentCode": null,
            "departmentName": "2321 - Instrumentation",
            "prtype": "Revenue Supply",
            "prSubType": "General",
            "preparer": "Sumit jain",
            "totalValue": 8000,
            "assignBuyer": "VIJAY CHAPLOT",
            "pR_STATUS": "Approved",
            "buyerstatus": "Pending",
            "totalcount": 14,
            "prLinesData":[
                {
                  "prtransid": 131796,
                  "prid": 66789,
                  "pR_NUM": "",
                  "itemcode": "100053031",
                  "iteM_DESCRIPTION": "VALVE ASSEMBLY; TYPE: LOAD UNLOAD,COMBIN. AUXILIARY; MANUFACTURER PART NO: 205831E3, MANUFACTURER: KAESER, MODEL/MACHINE NO: G3/4XQ16",
                  "uom": "NOS",
                  "quantity": 1,
                  "inProcessQUANTITY": 0,
                  "usedQty": 0,
                  "remQty": 1,
                  "rate": 15000,
                  "netAmount": 15000,
                  "buyerstatus": "In Process",
                  "rfqStatus": "Published",
                  "rfqno": "3223",
                  "poNo": "",
                  "poid": 0,
                  "stateName": "Madhya Pradesh",
                  "buyerid": 27043,
                  "siteID": 8,
                  "assignBuyer": "VIJAY CHAPLOT"
                },
                {
                  "prtransid": 131797,
                  "prid": 66789,
                  "pR_NUM": "",
                  "itemcode": "100053032",
                  "iteM_DESCRIPTION": "KIT, COMPRESSOR REPAIR; TYPE: MAINTENANCE OF AUX.VALVE; MANUFACTURER PART NO: 400940.2, MANUFACTURER: KAESER",
                  "uom": "NOS",
                  "quantity": 1,
                  "inProcessQUANTITY": 0,
                  "usedQty": 0,
                  "remQty": 1,
                  "rate": 5000,
                  "netAmount": 5000,
                  "buyerstatus": "In Process",
                  "rfqStatus": "Published",
                  "rfqno": "3223",
                  "poNo": "",
                  "poid": 0,
                  "stateName": "Madhya Pradesh",
                  "buyerid": 27043,
                  "siteID": 8,
                  "assignBuyer": "VIJAY CHAPLOT"
                }
              ]
        },
        {
            "sNo": 5,
            "prid": 66772,
            "pR_NUM": "PR23014402",
            "prepareR_ID": 27190,
            "description": "Coal mill seperator gear box level switch",
            "enterby": "Sumit jain",
            "enterdate": "2023-02-09T16:40:44.35",
            "approvedDate": "2023-02-11T19:07:05.923",
            "siteId": 2,
            "siteName": "102",
            "projecT_NAME": null,
            "departmentCode": null,
            "departmentName": "2321 - Instrumentation",
            "prtype": "Revenue Supply",
            "prSubType": "General",
            "preparer": "Sumit jain",
            "totalValue": 17460,
            "assignBuyer": "VIJAY CHAPLOT",
            "pR_STATUS": "Approved",
            "buyerstatus": "In Process",
            "totalcount": 14,
            "prLinesData":[
                {
                  "prtransid": 131796,
                  "prid": 66789,
                  "pR_NUM": "",
                  "itemcode": "100053031",
                  "iteM_DESCRIPTION": "VALVE ASSEMBLY; TYPE: LOAD UNLOAD,COMBIN. AUXILIARY; MANUFACTURER PART NO: 205831E3, MANUFACTURER: KAESER, MODEL/MACHINE NO: G3/4XQ16",
                  "uom": "NOS",
                  "quantity": 1,
                  "inProcessQUANTITY": 0,
                  "usedQty": 0,
                  "remQty": 1,
                  "rate": 15000,
                  "netAmount": 15000,
                  "buyerstatus": "In Process",
                  "rfqStatus": "Published",
                  "rfqno": "3223",
                  "poNo": "",
                  "poid": 0,
                  "stateName": "Madhya Pradesh",
                  "buyerid": 27043,
                  "siteID": 8,
                  "assignBuyer": "VIJAY CHAPLOT"
                },
                {
                  "prtransid": 131797,
                  "prid": 66789,
                  "pR_NUM": "",
                  "itemcode": "100053032",
                  "iteM_DESCRIPTION": "KIT, COMPRESSOR REPAIR; TYPE: MAINTENANCE OF AUX.VALVE; MANUFACTURER PART NO: 400940.2, MANUFACTURER: KAESER",
                  "uom": "NOS",
                  "quantity": 1,
                  "inProcessQUANTITY": 0,
                  "usedQty": 0,
                  "remQty": 1,
                  "rate": 5000,
                  "netAmount": 5000,
                  "buyerstatus": "In Process",
                  "rfqStatus": "Published",
                  "rfqno": "3223",
                  "poNo": "",
                  "poid": 0,
                  "stateName": "Madhya Pradesh",
                  "buyerid": 27043,
                  "siteID": 8,
                  "assignBuyer": "VIJAY CHAPLOT"
                }
              ]
        },
        {
            "sNo": 6,
            "prid": 66768,
            "pR_NUM": "PR23014398",
            "prepareR_ID": 27182,
            "description": "Transportation charges for lifting of X-Ray tube for X-ray 2 analyser",
            "enterby": "PUNEET JAIN",
            "enterdate": "2023-02-09T15:21:51.333",
            "approvedDate": "2023-02-11T19:07:38.453",
            "siteId": 2,
            "siteName": "102",
            "projecT_NAME": null,
            "departmentCode": null,
            "departmentName": "2321 - Instrumentation",
            "prtype": "Revenue Service",
            "prSubType": "General",
            "preparer": "PUNEET JAIN",
            "totalValue": 25000,
            "assignBuyer": "VIJAY CHAPLOT",
            "pR_STATUS": "Approved",
            "buyerstatus": "Pending",
            "totalcount": 14,
            "prLinesData":[
                {
                  "prtransid": 131796,
                  "prid": 66789,
                  "pR_NUM": "",
                  "itemcode": "100053031",
                  "iteM_DESCRIPTION": "VALVE ASSEMBLY; TYPE: LOAD UNLOAD,COMBIN. AUXILIARY; MANUFACTURER PART NO: 205831E3, MANUFACTURER: KAESER, MODEL/MACHINE NO: G3/4XQ16",
                  "uom": "NOS",
                  "quantity": 1,
                  "inProcessQUANTITY": 0,
                  "usedQty": 0,
                  "remQty": 1,
                  "rate": 15000,
                  "netAmount": 15000,
                  "buyerstatus": "In Process",
                  "rfqStatus": "Published",
                  "rfqno": "3223",
                  "poNo": "",
                  "poid": 0,
                  "stateName": "Madhya Pradesh",
                  "buyerid": 27043,
                  "siteID": 8,
                  "assignBuyer": "VIJAY CHAPLOT"
                },
                {
                  "prtransid": 131797,
                  "prid": 66789,
                  "pR_NUM": "",
                  "itemcode": "100053032",
                  "iteM_DESCRIPTION": "KIT, COMPRESSOR REPAIR; TYPE: MAINTENANCE OF AUX.VALVE; MANUFACTURER PART NO: 400940.2, MANUFACTURER: KAESER",
                  "uom": "NOS",
                  "quantity": 1,
                  "inProcessQUANTITY": 0,
                  "usedQty": 0,
                  "remQty": 1,
                  "rate": 5000,
                  "netAmount": 5000,
                  "buyerstatus": "In Process",
                  "rfqStatus": "Published",
                  "rfqno": "3223",
                  "poNo": "",
                  "poid": 0,
                  "stateName": "Madhya Pradesh",
                  "buyerid": 27043,
                  "siteID": 8,
                  "assignBuyer": "VIJAY CHAPLOT"
                }
              ]
        },
        {
            "sNo": 7,
            "prid": 66667,
            "pR_NUM": "PR23014323",
            "prepareR_ID": 27220,
            "description": "Fuse required for Danfoss VFD and MCC",
            "enterby": "Arpit Nagar",
            "enterdate": "2023-02-07T23:32:18.937",
            "approvedDate": "2023-02-09T18:58:13.627",
            "siteId": 8,
            "siteName": "110",
            "projecT_NAME": null,
            "departmentCode": null,
            "departmentName": "2331 - Electrical & Instrumentation",
            "prtype": "Revenue Supply",
            "prSubType": "General",
            "preparer": "Arpit Nagar",
            "totalValue": 4260,
            "assignBuyer": "VIJAY CHAPLOT",
            "pR_STATUS": "Approved",
            "buyerstatus": "Pending",
            "totalcount": 14,
            "prLinesData":[
                {
                  "prtransid": 131796,
                  "prid": 66789,
                  "pR_NUM": "",
                  "itemcode": "100053031",
                  "iteM_DESCRIPTION": "VALVE ASSEMBLY; TYPE: LOAD UNLOAD,COMBIN. AUXILIARY; MANUFACTURER PART NO: 205831E3, MANUFACTURER: KAESER, MODEL/MACHINE NO: G3/4XQ16",
                  "uom": "NOS",
                  "quantity": 1,
                  "inProcessQUANTITY": 0,
                  "usedQty": 0,
                  "remQty": 1,
                  "rate": 15000,
                  "netAmount": 15000,
                  "buyerstatus": "In Process",
                  "rfqStatus": "Published",
                  "rfqno": "3223",
                  "poNo": "",
                  "poid": 0,
                  "stateName": "Madhya Pradesh",
                  "buyerid": 27043,
                  "siteID": 8,
                  "assignBuyer": "VIJAY CHAPLOT"
                },
                {
                  "prtransid": 131797,
                  "prid": 66789,
                  "pR_NUM": "",
                  "itemcode": "100053032",
                  "iteM_DESCRIPTION": "KIT, COMPRESSOR REPAIR; TYPE: MAINTENANCE OF AUX.VALVE; MANUFACTURER PART NO: 400940.2, MANUFACTURER: KAESER",
                  "uom": "NOS",
                  "quantity": 1,
                  "inProcessQUANTITY": 0,
                  "usedQty": 0,
                  "remQty": 1,
                  "rate": 5000,
                  "netAmount": 5000,
                  "buyerstatus": "In Process",
                  "rfqStatus": "Published",
                  "rfqno": "3223",
                  "poNo": "",
                  "poid": 0,
                  "stateName": "Madhya Pradesh",
                  "buyerid": 27043,
                  "siteID": 8,
                  "assignBuyer": "VIJAY CHAPLOT"
                }
              ]
        },
        {
            "sNo": 8,
            "prid": 66611,
            "pR_NUM": "PR23014267",
            "prepareR_ID": 27189,
            "description": "Battery Charger for walkie talkie set use.",
            "enterby": "Ghanshyam Gochar",
            "enterdate": "2023-02-07T11:11:32.843",
            "approvedDate": "2023-02-11T18:58:30.68",
            "siteId": 2,
            "siteName": "102",
            "projecT_NAME": null,
            "departmentCode": null,
            "departmentName": "2321 - Instrumentation",
            "prtype": "Revenue Supply",
            "prSubType": "General",
            "preparer": "Ghanshyam Gochar",
            "totalValue": 20755,
            "assignBuyer": "VIJAY CHAPLOT",
            "pR_STATUS": "Approved",
            "buyerstatus": "Pending",
            "totalcount": 14,
            "prLinesData":[
                {
                  "prtransid": 131796,
                  "prid": 66789,
                  "pR_NUM": "",
                  "itemcode": "100053031",
                  "iteM_DESCRIPTION": "VALVE ASSEMBLY; TYPE: LOAD UNLOAD,COMBIN. AUXILIARY; MANUFACTURER PART NO: 205831E3, MANUFACTURER: KAESER, MODEL/MACHINE NO: G3/4XQ16",
                  "uom": "NOS",
                  "quantity": 1,
                  "inProcessQUANTITY": 0,
                  "usedQty": 0,
                  "remQty": 1,
                  "rate": 15000,
                  "netAmount": 15000,
                  "buyerstatus": "In Process",
                  "rfqStatus": "Published",
                  "rfqno": "3223",
                  "poNo": "",
                  "poid": 0,
                  "stateName": "Madhya Pradesh",
                  "buyerid": 27043,
                  "siteID": 8,
                  "assignBuyer": "VIJAY CHAPLOT"
                },
                {
                  "prtransid": 131797,
                  "prid": 66789,
                  "pR_NUM": "",
                  "itemcode": "100053032",
                  "iteM_DESCRIPTION": "KIT, COMPRESSOR REPAIR; TYPE: MAINTENANCE OF AUX.VALVE; MANUFACTURER PART NO: 400940.2, MANUFACTURER: KAESER",
                  "uom": "NOS",
                  "quantity": 1,
                  "inProcessQUANTITY": 0,
                  "usedQty": 0,
                  "remQty": 1,
                  "rate": 5000,
                  "netAmount": 5000,
                  "buyerstatus": "In Process",
                  "rfqStatus": "Published",
                  "rfqno": "3223",
                  "poNo": "",
                  "poid": 0,
                  "stateName": "Madhya Pradesh",
                  "buyerid": 27043,
                  "siteID": 8,
                  "assignBuyer": "VIJAY CHAPLOT"
                }
              ]
        },
        {
            "sNo": 9,
            "prid": 66592,
            "pR_NUM": "PR23014248",
            "prepareR_ID": 27220,
            "description": "Relay controller (Mini PLC) for magnetic separator",
            "enterby": "Arpit Nagar",
            "enterdate": "2023-02-06T18:36:09.37",
            "approvedDate": "2023-02-09T09:33:57.343",
            "siteId": 8,
            "siteName": "110",
            "projecT_NAME": null,
            "departmentCode": null,
            "departmentName": "2331 - Electrical & Instrumentation",
            "prtype": "Revenue Supply",
            "prSubType": "General",
            "preparer": "Arpit Nagar",
            "totalValue": 35000,
            "assignBuyer": "VIJAY CHAPLOT",
            "pR_STATUS": "Approved",
            "buyerstatus": "Pending",
            "totalcount": 14,
            "prLinesData":[
                {
                  "prtransid": 131796,
                  "prid": 66789,
                  "pR_NUM": "",
                  "itemcode": "100053031",
                  "iteM_DESCRIPTION": "VALVE ASSEMBLY; TYPE: LOAD UNLOAD,COMBIN. AUXILIARY; MANUFACTURER PART NO: 205831E3, MANUFACTURER: KAESER, MODEL/MACHINE NO: G3/4XQ16",
                  "uom": "NOS",
                  "quantity": 1,
                  "inProcessQUANTITY": 0,
                  "usedQty": 0,
                  "remQty": 1,
                  "rate": 15000,
                  "netAmount": 15000,
                  "buyerstatus": "In Process",
                  "rfqStatus": "Published",
                  "rfqno": "3223",
                  "poNo": "",
                  "poid": 0,
                  "stateName": "Madhya Pradesh",
                  "buyerid": 27043,
                  "siteID": 8,
                  "assignBuyer": "VIJAY CHAPLOT"
                },
                {
                  "prtransid": 131797,
                  "prid": 66789,
                  "pR_NUM": "",
                  "itemcode": "100053032",
                  "iteM_DESCRIPTION": "KIT, COMPRESSOR REPAIR; TYPE: MAINTENANCE OF AUX.VALVE; MANUFACTURER PART NO: 400940.2, MANUFACTURER: KAESER",
                  "uom": "NOS",
                  "quantity": 1,
                  "inProcessQUANTITY": 0,
                  "usedQty": 0,
                  "remQty": 1,
                  "rate": 5000,
                  "netAmount": 5000,
                  "buyerstatus": "In Process",
                  "rfqStatus": "Published",
                  "rfqno": "3223",
                  "poNo": "",
                  "poid": 0,
                  "stateName": "Madhya Pradesh",
                  "buyerid": 27043,
                  "siteID": 8,
                  "assignBuyer": "VIJAY CHAPLOT"
                }
              ]
        },
        {
            "sNo": 10,
            "prid": 66587,
            "pR_NUM": "PR23014243",
            "prepareR_ID": 27182,
            "description": "X-Ray tube required for X-ray 2 analyser",
            "enterby": "PUNEET JAIN",
            "enterdate": "2023-02-06T18:18:07.997",
            "approvedDate": "2023-02-11T13:33:08.17",
            "siteId": 2,
            "siteName": "102",
            "projecT_NAME": null,
            "departmentCode": null,
            "departmentName": "2321 - Instrumentation",
            "prtype": "Revenue Supply",
            "prSubType": "General",
            "preparer": "PUNEET JAIN",
            "totalValue": 3800000,
            "assignBuyer": "VIJAY CHAPLOT",
            "pR_STATUS": "Approved",
            "buyerstatus": "Pending",
            "totalcount": 14,
            "prLinesData":[
                {
                  "prtransid": 131796,
                  "prid": 66789,
                  "pR_NUM": "",
                  "itemcode": "100053031",
                  "iteM_DESCRIPTION": "VALVE ASSEMBLY; TYPE: LOAD UNLOAD,COMBIN. AUXILIARY; MANUFACTURER PART NO: 205831E3, MANUFACTURER: KAESER, MODEL/MACHINE NO: G3/4XQ16",
                  "uom": "NOS",
                  "quantity": 1,
                  "inProcessQUANTITY": 0,
                  "usedQty": 0,
                  "remQty": 1,
                  "rate": 15000,
                  "netAmount": 15000,
                  "buyerstatus": "In Process",
                  "rfqStatus": "Published",
                  "rfqno": "3223",
                  "poNo": "",
                  "poid": 0,
                  "stateName": "Madhya Pradesh",
                  "buyerid": 27043,
                  "siteID": 8,
                  "assignBuyer": "VIJAY CHAPLOT"
                },
                {
                  "prtransid": 131797,
                  "prid": 66789,
                  "pR_NUM": "",
                  "itemcode": "100053032",
                  "iteM_DESCRIPTION": "KIT, COMPRESSOR REPAIR; TYPE: MAINTENANCE OF AUX.VALVE; MANUFACTURER PART NO: 400940.2, MANUFACTURER: KAESER",
                  "uom": "NOS",
                  "quantity": 1,
                  "inProcessQUANTITY": 0,
                  "usedQty": 0,
                  "remQty": 1,
                  "rate": 5000,
                  "netAmount": 5000,
                  "buyerstatus": "In Process",
                  "rfqStatus": "Published",
                  "rfqno": "3223",
                  "poNo": "",
                  "poid": 0,
                  "stateName": "Madhya Pradesh",
                  "buyerid": 27043,
                  "siteID": 8,
                  "assignBuyer": "VIJAY CHAPLOT"
                }
              ]
        },
        {
            "sNo": 11,
            "prid": 66405,
            "pR_NUM": "PR23014071",
            "prepareR_ID": 27300,
            "description": "Bucket Elevator BDS to be replaced with new contactless time sensor as existing supplied arrangement is not operating properly",
            "enterby": "Kapil Mantri",
            "enterdate": "2023-02-02T17:30:39.593",
            "approvedDate": "2023-02-11T19:01:28.003",
            "siteId": 2,
            "siteName": "102",
            "projecT_NAME": null,
            "departmentCode": null,
            "departmentName": "2321 - Instrumentation",
            "prtype": "Revenue Supply",
            "prSubType": "General",
            "preparer": "Kapil Mantri",
            "totalValue": 56000,
            "assignBuyer": "VIJAY CHAPLOT",
            "pR_STATUS": "Approved",
            "buyerstatus": "Pending",
            "totalcount": 14,
            "prLinesData":[
                {
                  "prtransid": 131796,
                  "prid": 66789,
                  "pR_NUM": "",
                  "itemcode": "100053031",
                  "iteM_DESCRIPTION": "VALVE ASSEMBLY; TYPE: LOAD UNLOAD,COMBIN. AUXILIARY; MANUFACTURER PART NO: 205831E3, MANUFACTURER: KAESER, MODEL/MACHINE NO: G3/4XQ16",
                  "uom": "NOS",
                  "quantity": 1,
                  "inProcessQUANTITY": 0,
                  "usedQty": 0,
                  "remQty": 1,
                  "rate": 15000,
                  "netAmount": 15000,
                  "buyerstatus": "In Process",
                  "rfqStatus": "Published",
                  "rfqno": "3223",
                  "poNo": "",
                  "poid": 0,
                  "stateName": "Madhya Pradesh",
                  "buyerid": 27043,
                  "siteID": 8,
                  "assignBuyer": "VIJAY CHAPLOT"
                },
                {
                  "prtransid": 131797,
                  "prid": 66789,
                  "pR_NUM": "",
                  "itemcode": "100053032",
                  "iteM_DESCRIPTION": "KIT, COMPRESSOR REPAIR; TYPE: MAINTENANCE OF AUX.VALVE; MANUFACTURER PART NO: 400940.2, MANUFACTURER: KAESER",
                  "uom": "NOS",
                  "quantity": 1,
                  "inProcessQUANTITY": 0,
                  "usedQty": 0,
                  "remQty": 1,
                  "rate": 5000,
                  "netAmount": 5000,
                  "buyerstatus": "In Process",
                  "rfqStatus": "Published",
                  "rfqno": "3223",
                  "poNo": "",
                  "poid": 0,
                  "stateName": "Madhya Pradesh",
                  "buyerid": 27043,
                  "siteID": 8,
                  "assignBuyer": "VIJAY CHAPLOT"
                }
              ]
        }]


export const categoryList:any=[
    {
        "CategoryID":1,
        "CategoryName":"test",
        "Description":"Testing descritpoin"
    },
    {
        "CategoryID":1,
        "CategoryName":"test 1",
        "Description":"Testing descritpoin"
    },
    {
        "CategoryID":1,
        "CategoryName":"test 2",
        "Description":"Testing descritpoin"
    }
]

export const categoryDetail:any=[
    {
        "ProductID":1,
        "ProductName":"test",
        "UnitPrice":"Testing unit price"
    },
    {
        "ProductID":1,
        "ProductName":"test 3",
        "UnitPrice":"Testing unit price"
    },
    {
        "ProductID":1,
        "ProductName":"test 4",
        "UnitPrice":"Testing unit price"
    }
]